version: '3.8'
services:
  local-db:
    platform: linux/x86_64
    image: library/mysql
    container_name: delivery_system
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=delivery_system
      