name: CI Kjh

on:
  pull_request:
    branches:
      - develop

env:
  IMAGE_TAG: delivery-system

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Build Docker Image
        run: docker build -t $IMAGE_TAG
      
      - name: Run Tests
        run: docker run $IMAGE_TAG sh -c 'npm run test'

